server:
  port: 9096

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: sandbox-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
        username: nacos
        password: "#Alone117"
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
        port: 8719
      web-context-unify: false # 关闭上下文整合，启用链路模式
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_oj?useSSL=false&characterEncoding=UTF-8
    username: root
    password: Alone117

# 日志配置
logging:
  level:
    com.david: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.mybatis: DEBUG

docker:
  host: unix:///var/run/docker.sock # Docker守护进程地址
  max-connections: 100 # 最大连接数
  connection:
    timeout: 30 # 连接超时时间（秒）
  response:
    timeout: 45 # 响应超时时间（秒）
