spring:
  kafka:
    bootstrap-servers: 192.168.1.102:9092
    consumer:
      group-id: judge-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
