spring:
  application:
    name: problems-service # 应用名称
  cloud:
    nacos:
      discovery:
        server-addr: 129.204.227.158:8848 #配置Nacos地址
        username: nacos
        password: "#Alone117"
    sentinel:
      transport:
        dashboard: 129.204.227.158:9090
        port: 8719
      web-context-unify: false # 关闭上下文整合，启用链路模式