spring:
  application:
    name: gateway-service # 应用名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
        username: nacos
        password: "#Alone117"
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
        port: 8719
      web-context-unify: false # 关闭上下文整合，启用链路模式
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现
          lower-case-service-id: true # 服务名小写
      routes: # 认证服务路由
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: user-service-user
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
        - id: user-service-role
          uri: lb://user-service
          predicates:
            - Path=/role/api/**
          filters:
            - StripPrefix=0
        - id: problems-service-problems
          uri: lb://problems-service
          predicates:
            - Path=/api/problems/**
          filters:
            - StripPrefix=0
        - id: problems-service-tags
          uri: lb://problems-service
          predicates:
            - Path=/api/tags/**
          filters:
            - StripPrefix=0
        - id: problems-service-problem-stats
          uri: lb://problems-service
          predicates:
            - Path=/api/problem-stats/**
          filters:
            - StripPrefix=0
        - id: problems-service-categories
          uri: lb://problems-service
          predicates:
            - Path=/api/categories/**
          filters:
            - StripPrefix=0
        - id: problems-service-difficulties
          uri: lb://problems-service
          predicates:
            - Path=/api/difficulties/**
          filters:
            - StripPrefix=0
        - id: problems-service-testcase-steps
          uri: lb://problems-service
          predicates:
            - Path=/api/testcase-steps/**
          filters:
            - StripPrefix=0
        - id: problems-service-testcase-groups
          uri: lb://problems-service
          predicates:
            - Path=/api/testcase-groups/**
          filters:
            - StripPrefix=0
        - id: problems-service-testcases
          uri: lb://problems-service
          predicates:
            - Path=/api/testcases/**
          filters:
            - StripPrefix=0
        - id: problems-service-problem-locales
          uri: lb://problems-service
          predicates:
            - Path=/api/problem-locales/**
          filters:
            - StripPrefix=0
        - id: problems-service-problem-language-configs
          uri: lb://problems-service
          predicates:
            - Path=/api/problem-language-configs/**
          filters:
            - StripPrefix=0
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin,*
        - AddResponseHeader=Access-Control-Allow-Methods,GET,POST,PUT,DELETE,OPTIONS
        - AddResponseHeader=Access-Control-Allow-Headers,*
        - AddResponseHeader=Access-Control-Max-Age,3600