server:
  port: 9090

spring:
  application:
    name: gateway # 应用名称
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
        username: nacos
        password: "#Alone117"
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
        port: 8719
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现
          lower-case-service-id: true # 服务名小写
      routes:
        # 认证服务路由
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: user-service-user
          uri: lb://user-service
          predicates:
            - Path=/user/api/**
          filters:
            - StripPrefix=0
        - id: user-service-role
          uri: lb://user-service
          predicates:
            - Path=/role/api/**
          filters:
            - StripPrefix=0
        - id: problems-service-problems
          uri: lb://problems-service
          predicates:
            - Path=/problems/api/**
          filters:
            - StripPrefix=0
        - id: problems-service-submissions
          uri: lb://problems-service
          predicates:
            - Path=/submissions/api/**
          filters:
            - StripPrefix=0
        - id: problems-service-questions
          uri: lb://problems-service
          predicates:
            - Path=/problem-bank/api/**
          filters:
            - StripPrefix=0
        - id: judge-service
          uri: lb://judge-service
          predicates:
            - Path=/judge/api/**
          filters:
            - StripPrefix=0
        - id: problems-service-solution
          uri: lb://problems-service
          predicates:
            - Path=/solutions/api/**
          filters:
            - StripPrefix=0
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin,*
        - AddResponseHeader=Access-Control-Allow-Methods,GET,POST,PUT,DELETE,OPTIONS
        - AddResponseHeader=Access-Control-Allow-Headers,*
        - AddResponseHeader=Access-Control-Max-Age,3600

# 日志配置
logging:
  level:
    com.david: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
