logging:
  level:
    com.david: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.mybatis: DEBUG
    com.david.log.commons.core.business: INFO
    com.david.log.commons.core.performance: DEBUG
    com.david.log.commons.core.security: WARN
    com.david.log.commons.core.exception: ERROR