server:
  port: 9091

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: authentication # 应用名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
        username: nacos
        password: "#Alone117"
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
        port: 8719
    loadbalancer:
      nacos:
        enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_oj?useSSL=false&characterEncoding=UTF-8
    username: root
    password: Alone117
  data:
    redis: # 基础 Redis 连接配置
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000 # 使用毫秒格式，兼容 Redis Lettuce
      password: Alone117
      lettuce:
        pool:
          max-active: 20 # 最大连接数
          max-wait: -1 # 最大阻塞等待时间(负数表示无限制)
          max-idle: 5 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数

      # Redis Commons 扩展配置
      commons: # 是否启用 Redis Commons 功能
        enabled: true

        # 缓存配置
        cache: # 默认缓存过期时间
          default-ttl: PT1H
          # 缓存键前缀
          key-prefix: "springoj:cache:"
          # 是否启用空值缓存
          enable-null-values: false
          # 序列化类型
          serialization-type: "JSON"

        # 分布式锁配置
        lock: # 默认等待时间
          default-wait-time: PT10S
          # 默认租约时间
          default-lease-time: PT30S
          # 重试次数
          retry-attempts: 3
          # 锁键前缀
          key-prefix: "springoj:lock:"

        # 事务配置
        transaction: # 是否启用自动回滚
          enable-auto-rollback: true
          # 事务超时时间
          timeout: PT30S
          # 是否启用事务日志
          enable-transaction-log: false

        # 监控指标配置
        metrics: # 是否启用监控
          enabled: true
          # 慢查询阈值
          slow-query-threshold: PT0.1S
          # 是否启用详细指标
          enable-detailed-metrics: true
          # 指标收集间隔
          collection-interval: PT30S

  # 日志配置

  mail:
    host: smtp.163.com # 你邮箱的smtp地址
    username: davidblog117@163.com # 申请了smtp的邮箱
    password: VIBXJWEUSYVJMJXK # SMTP服务的秘钥
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.david.entity

# LogCommons 统一日志组件配置示例
log-commons: # 全局配置
  enabled: true # 是否启用日志组件
  default-async: true # 默认是否使用异步处理
  buffer-size: 1000 # 缓冲区大小
  flush-interval-seconds: 5 # 刷新间隔(秒)
  batch-size: 50 # 批处理大小

  # 模块配置
  modules:
    business: # 业务日志模块
      enabled: true
      level: INFO
      async: true
      metrics-enabled: true
    performance: # 性能日志模块
      enabled: true
      level: DEBUG
      async: true
      metrics-enabled: true
    security: # 安全日志模块
      enabled: true
      level: WARN
      async: false # 安全日志使用同步处理
      metrics-enabled: true
    exception: # 异常日志模块
      enabled: true
      level: ERROR
      async: false # 异常日志使用同步处理
      metrics-enabled: true

  # 敏感信息脱敏配置
  sensitive:
    enabled: true
    mask-pattern: "***"
    keywords: # 敏感关键词
      - password
      - pwd
      - passwd
      - token
      - secret
      - apikey
      - credit
      - card
      - bank
    patterns: # 敏感数据正则表达式
      - "1[3-9]\\d{9}" # 手机号
      - "[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}" # 邮箱
      - "\\d{17}[\\dXx]" # 身份证号
      - "\\d{13,19}" # 银行卡号
      - "[a-zA-Z0-9]{32,}" # 可能的密钥

  # 指标收集配置
  metrics:
    enabled: false
    prefix: "log.commons"
    detailed: true

# Spring Boot Actuator配置(可选)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: false

# 日志输出配置(基于Logback)
logging:
  level:
    com.david: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.mybatis: DEBUG
    com.david.log.commons.core.business: INFO
    com.david.log.commons.core.performance: DEBUG
    com.david.log.commons.core.security: WARN
    com.david.log.commons.core.exception: ERROR
