server:
  port: 9091

spring:
  profiles:
    active: myself
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: authentication # 应用名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
        username: nacos
        password: '#Alone117'
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
        port: 8719
    loadbalancer:
      nacos:
        enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_oj?useSSL=false&characterEncoding=UTF-8
    username: root
    password: Alone117
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000 # 使用毫秒格式，兼容 Redis Lettuce
      password: Alone117
      lettuce:
        pool:
          max-active: 20 # 最大连接数
          max-wait: -1 # 最大阻塞等待时间(负数表示无限制)
          max-idle: 5 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数
  mail:
    host:  # 你邮箱的smtp地址
    username:  # 申请了smtp的邮箱
    password:    # SMTP服务的秘钥
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.david.entity

# 日志配置
logging:
  level:
    com.david: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.mybatis: DEBUG