spring:
  data:
    redis:
      host: 192.168.139.49
      port: 6379
      database: 0
      timeout: 1800000
      password: Alone117
      lettuce:
        pool:
          max-active: 20
          max-idle: 5
          min-idle: 2
