server:
  port: 9093

spring:
  application:
    name: user-service # 应用名称
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
        username: nacos
        password: "#Alone117"
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
        port: 8719
      web-context-unify: false # 关闭上下文整合，启用链路模式
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_oj?useSSL=false&characterEncoding=UTF-8
    username: root
    password: Alone117
  data:
    redis:
      # 基础 Redis 连接配置
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000 # 使用毫秒格式，兼容 Redis Lettuce
      password: Alone117
      lettuce:
        pool:
          max-active: 20 # 最大连接数
          max-wait: -1 # 最大阻塞等待时间(负数表示无限制)
          max-idle: 5 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数

      # Redis Commons 扩展配置
      commons:
        # 是否启用 Redis Commons 功能
        enabled: true

        # 缓存配置
        cache:
          # 默认缓存过期时间
          default-ttl: PT1H
          # 缓存键前缀
          key-prefix: "springoj:cache:"
          # 是否启用空值缓存
          enable-null-values: false
          # 序列化类型
          serialization-type: "JSON"

        # 分布式锁配置
        lock:
          # 默认等待时间
          default-wait-time: PT10S
          # 默认租约时间
          default-lease-time: PT30S
          # 重试次数
          retry-attempts: 3
          # 锁键前缀
          key-prefix: "springoj:lock:"

        # 事务配置
        transaction:
          # 是否启用自动回滚
          enable-auto-rollback: true
          # 事务超时时间
          timeout: PT30S
          # 是否启用事务日志
          enable-transaction-log: false

        # 监控指标配置
        metrics:
          # 是否启用监控
          enabled: true
          # 慢查询阈值
          slow-query-threshold: PT0.1S
          # 是否启用详细指标
          enable-detailed-metrics: false
          # 指标收集间隔
          collection-interval: PT30S


# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# 日志配置
logging:
  level:
    com.david: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.mybatis: DEBUG