spring:
  data:
    redis: # 基础 Redis 连接配置
      host: 192.168.139.49
      port: 6379
      database: 0
      timeout: 1800000 # 使用毫秒格式，兼容 Redis Lettuce
      password: Alone117
      lettuce:
        pool:
          max-active: 20 # 最大连接数
          max-idle: 5 # 最大空闲连接数
          min-idle: 2 # 最小空闲连接数
      # Redis Commons 扩展配置
      commons: # 是否启用 Redis Commons 功能
        enabled: true
        # 缓存配置
        cache: # 默认缓存过期时间
          default-ttl: PT1H
          # 缓存键前缀
          key-prefix: "springoj:cache:"
          # 是否启用空值缓存
          enable-null-values: false
          # 序列化类型
          serialization-type: "JSON"
        # 分布式锁配置
        lock: # 默认等待时间
          default-wait-time: PT10S
          # 默认租约时间
          default-lease-time: PT30S
          # 重试次数
          retry-attempts: 3
          # 锁键前缀
          key-prefix: "springoj:lock:"
        # 事务配置
        transaction: # 是否启用自动回滚
          enable-auto-rollback: true
          # 事务超时时间
          timeout: PT30S
          # 是否启用事务日志
          enable-transaction-log: false
        # 监控指标配置
        metrics: # 是否启用监控
          enabled: false
          # 慢查询阈值
          slow-query-threshold: PT0.1S
          # 是否启用详细指标
          enable-detailed-metrics: false
          # 指标收集间隔
          collection-interval: PT30S
