spring:
  datasource:
    druid:
      initial-size: 5
      min-idle: 2
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      keep-alive: true
      time-between-eviction-runs-millis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/spring_oj?useSSL=false&characterEncoding=UTF-8
    username: root
    password: Alone117
