server:
  port: 9095

spring:
  application:
    name: judge-service # 应用名称
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 10.25.0.11:8848 #配置Nacos地址
        username: nacos
        password: '#Alone117'
    sentinel:
      transport:
        dashboard: 10.25.0.12:8080
        port: 8719
      web-context-unify: false # 关闭上下文整合，启用链路模式
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_oj?useSSL=false&characterEncoding=UTF-8
    username: root
    password: Alone117


# 判题机配置

  sandbox:
    service-url: http://localhost:9096  # 沙箱服务地址

# 日志配置
logging:
  level:
    com.david: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.mybatis: DEBUG